<a href="https://colab.research.google.com/github/RosanaCutiePie/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Elevado_Nebres_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratory 6: Matrix Operations
Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more

## Objectives
At the end of this activity you will be able to:

1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [150]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix  its transpose is denoted as . So for example

$$ A = \begin{bmatrix} 1 & 2 & 5 \\  5 & -1 & 0 \\ 0 & -3 & 3 \end{bmatrix} $$


$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using np.transpose() or using the T method.


In [151]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [152]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [153]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [154]:
np.array_equiv(AT1, AT2)

True

In [155]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [156]:
np.transpose(B).shape

(4, 2)

In [157]:
B.T.shape

(4, 2)

### Try to create your own matrix (you can try non-squares) to test transposition.

In [158]:
## Try out your code here.
Z=np.array([
    [-1,2,5],
    [0,-3,3]        
])
Z.shape

(2, 3)

In [159]:
np.transpose(Z).shape

(3, 2)

In [160]:
Z.T.shape

(3, 2)

In [161]:
ZT = Z.T
ZT

array([[-1,  0],
       [ 2, -3],
       [ 5,  3]])

## DOT PRODUCT /  INNER PRODUCT

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices _X_ and _Y_:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:

$$X ⋅ Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)} \end{bmatrix}$$

So if we assign values to _X_ and _Y_:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$
$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$

This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [162]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [163]:
np.array_equiv(X, Y)

False

In [164]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [165]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [166]:
X @ Y

array([[3, 4],
       [2, 2]])

In [167]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [168]:
D = np.array([
    [2,1,0],
    [3,1,7],
    [6,5,2]
])
E = np.array([
    [-3,1,5],
    [1,7,6],
    [7,7,3]
])

In [169]:
D @ E

array([[-5,  9, 16],
       [41, 59, 42],
       [ 1, 55, 66]])

In [170]:
D.dot(E)

array([[-5,  9, 16],
       [41, 59, 42],
       [ 1, 55, 66]])

In [171]:
np.matmul(D, E)

array([[-5,  9, 16],
       [41, 59, 42],
       [ 1, 55, 66]])

In [172]:
np.dot(D, E)

array([[-5,  9, 16],
       [41, 59, 42],
       [ 1, 55, 66]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same.
So given a matrix _A_ with a shape of _(a,b)_ where _a_ and _b_ are any integers. If we want to do a dot product between _A_ and another matrix _B_, then matrix _B_ should have a shape of _(b,c)_ where _b_ and _c_ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case _A_ has a shape of _(3,2)_, _B_ has a shape of _(3,2)_ and _C_ has a shape of _(2,3)_. So the only matrix pairs that is eligible to perform dot product is matrices _A_ ⋅ _C_, or _B_ ⋅ _C_.



In [173]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [174]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [175]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [176]:
A @ B

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix _A_ with a shape of _(a,b)_ and matrix _B_ with a shape of _(b,c)_, _A_ ⋅ _B_  should have a shape _(a,c)_.

In [177]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [178]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [179]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [180]:
X @ Y.T

array([[13]])

And youcan see that when you try to multiply A and B, it returns ValueError pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:

1. $A ⋅ B \neq B ⋅ A$
2. $A ⋅ (B ⋅ C) = (A ⋅ B) ⋅ C$
3. $A ⋅ (B+C) = A ⋅ B + A ⋅ C$
4. $(B+C) ⋅ A = B ⋅ A + C ⋅ A$
5. $A ⋅ I = A$
6. $A ⋅ ∅ = ∅$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [181]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [182]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [183]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [185]:
np.array_equal(A@B, B@A)

False

In [186]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [187]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [188]:
np.array_equal(E, X)

False

In [189]:
np.array_equiv(E, F)

True

In [190]:
np.eye(A)

TypeError: ignored

In [191]:
A @ E

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [192]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [193]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [194]:
np.array_equal(a_dot_z,z_mat)

True

In [195]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

### Determinant
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.
The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:

$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$

We can compute for the determinant as:

$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$

So if we have $A$ as:

$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using np.linalg.det().



In [196]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [197]:
B = np.array([
              [1, 5, 2],
              [3, -1 ,-1],
              [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

In [198]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

###Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:

$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$

First, we need to get the determinant of $M$.

$$|M| = (1)(5)-(-3)(7) = 26$$

Next, we need to reform the matrix into the inverse form:

$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$

So that will be:

$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$

For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use np.linalg.inv().



In [199]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [200]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [201]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [202]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:

$$M · M^{-1} = I$$



In [203]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

# Activity

###Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [101]:
A = np.array([[1,2,-1,4],[2,-2,1,-4],[2,1,2,0],[0,1,-1,8]])
B = np.array([[0,-3,1,2],[3,5,0,-1],[2,3,-1,1],[0,0,3,-1]])
C = np.array([[4,0,3,-1],[0,2,-2,1],[6,-5,4,1],[2,1,-3,4]])

$A ⋅ B \neq B ⋅ A$


In [98]:
X = np.dot(A,B)
print(X)

[[  4   4  14  -5]
 [ -4 -13 -11  11]
 [  7   5   0   5]
 [  1   2  25 -10]]


In [96]:
Y = np.dot(B,A)
print(Y)

[[ -4   9  -3  28]
 [ 13  -5   3 -16]
 [  6  -2  -2   4]
 [  6   2   7  -8]]


In [100]:
np.array_equal(X,Y)

False

$A ⋅ (B ⋅ C) = (A ⋅ B) ⋅ C$

In [105]:
D = np.dot(B,C)


In [106]:
E = np.dot(A,B)


In [108]:
F = np.dot(A,D)
print(F)

[[  90  -67   75   -6]
 [ -60   40  -63   24]
 [  38   15   -4   18]
 [ 134 -131  129  -14]]


In [109]:
G = np.dot(E,C)
print(G)

[[  90  -67   75   -6]
 [ -60   40  -63   24]
 [  38   15   -4   18]
 [ 134 -131  129  -14]]


In [110]:
np.array_equal(F,G)

True

$A ⋅ (B+C) = A ⋅ B + A ⋅ C$

In [113]:
H = np.dot(A, B+C)
print(H)

[[ 10  17  -3  11]
 [  2 -26  15  -8]
 [ 27  -3  12   6]
 [ 11  17  -5  22]]


In [115]:
I = np.dot(A,B) + np.dot(A,C)
print(I)

[[ 10  17  -3  11]
 [  2 -26  15  -8]
 [ 27  -3  12   6]
 [ 11  17  -5  22]]


In [116]:
np.array_equal(H,I)

True

$(B+C) ⋅ A = B ⋅ A + C ⋅ A$

In [117]:
J = np.dot(B+C, A)
print(J)

[[  6  19   0  36]
 [ 13 -10   0 -16]
 [ 10  25  -6  56]
 [  4   5  -4  28]]


In [119]:
K = np.dot(B,A) + np.dot(C,A)
print(K)

[[  6  19   0  36]
 [ 13 -10   0 -16]
 [ 10  25  -6  56]
 [  4   5  -4  28]]


In [120]:
np.array_equal(J,K)

True

$A ⋅ I = A$

In [129]:
L = np.identity(4)
print(L)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [130]:
M = np.dot(A,L)
print(M)

[[ 1.  2. -1.  4.]
 [ 2. -2.  1. -4.]
 [ 2.  1.  2.  0.]
 [ 0.  1. -1.  8.]]


In [131]:
np.array_equal(M,A)

True

$A ⋅ ∅ = ∅$ 

In [141]:
N = np.dot(A, np.empty((4,0)))
print(N)

[]


In [143]:
O = np.empty((4,0))
print(O)

[]


In [144]:
np.array_equal(N,O)

True